name: Build app
on:
  workflow_dispatch:
jobs:
  build-with-artifacts:
    strategy:
      matrix:
        os:
          [
            { name: 'linux', image: 'ubuntu-latest' },
            { name: 'windows', image: 'windows-latest' }
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - name: Add msbuild to PATH
        if: runner.os == 'windows'
        uses: microsoft/setup-msbuild@v1.1
      - name: Install WiX build tools
        if: runner.os == 'windows'
        run: dotnet tool install --global wix
      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run make
      - name: Upload squirrel.windows artifacts
        if: runner.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-squirrel
          path: out/make/squirrel.windows
      - name: Upload msi artifacts
        if: runner.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-msi
          path: out/make/wix
      - name: Upload zip.windows artifacts
        if: runner.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-zip.windows
          path: out/make/zip
      - name: Upload zip.linux artifacts
        if: runner.os == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-zip.linux
          path: out/make/zip
      - name: Upload deb artifacts
        if: runner.os == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-deb
          path: out/make/deb
      - name: Upload rpm artifacts
        if: runner.os == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-rpm
          path: out/make/rpm